micronaut:
  server:
    http-version: 2.0
    port: -1
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins:
            - http://localhost:8080
          allowedMethods:
            - POST
          allowedHeaders:
  application:
    name: micronaut-rest-example
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

endpoints:
  all:
    path: "/actuator"
    enabled: false
    sensitive: true
    #    port: 8095 should be defined by devops
  health:
    enabled: true
    sensitive: false # non-secured endpoint
    details-visible: ANONYMOUS # show details for everyone
    url:
      enabled: true
  readiness:
    enabled: true
    sensitive: false
  prometheus:
    enabled: true
    sensitive: false
  routes:
    enabled: true
    sensitive: false

service:
  application:
    message: "Processing Transfer Request"
