openapi: 3.0.1
info:
  title: Transfer Service
  description: Simple REST Service example implementated using Micronaut
  contact:
    email: jpmlabs@jpmorgan.com
  version: 0.0.1
paths:
  /transfer:
    post:
      summary: "Add a transfer request"
      operationId: "addPet"
      requestBody:
        description: "Transfer details"
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/json/TransferDetails.json"
            example:
              userId: 01FM4JE6DVQ9MP08YREJRW6AYZ
              amount: 10
              accountFrom: "12345678"
              accountTo: "12345679"
      responses:
        "202":
          description: "Transfer Request Accepted"
          content:
            application/json:
              schema:
                type: string
